services:
  - type: web
    name: cal-com-clone-backend
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate --noinput && python manage.py collectstatic --noinput
    startCommand: gunicorn server.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: cal-com-clone.onrender.com,.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://cal-com-clone-roan.vercel.app
      - key: CSRF_TRUSTED_ORIGINS
        value: https://cal-com-clone-roan.vercel.app
